# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-26 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
