# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-26 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20180726_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
